title: Akpevwenoghene Gbenedio
logo: Image tech.jpg
description:Data Analyst with experience using microsoft Excel for report automation, SQL for data manipulation interpretation and Power Bi for creating business insights.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
